---
title: Paper de Prueba IPO RGit
format:
  docx:
    number-sections: true
  html: 
    code-fold: true
    html-math-method: katex
    number-sections: true
  pdf:
    classoption: 10pt
    geometry: 
      - top=30mm
      - left=20mm
    template-partials: 
      - title.tex
    keep-tex: true
    number-sections: true
    include-in-header:
      text: |
        \usepackage[noblocks]{authblk}
        \renewcommand*{\Authsep}{, }
        \renewcommand*{\Authand}{, }
        \renewcommand*{\Authands}{, }
        \renewcommand\Affilfont{\small}
        \renewcommand\Affilfont{\small}
        \usepackage{mathptmx} % Times
editor: source
author: "Laboratorio de Investigación Social Abierta"
citeproc: true
---

```{r setup, include=FALSE}
 knitr::opts_chunk$set(echo=FALSE, warning = FALSE,message = FALSE, cache = TRUE,out.width = '85%',fig.pos= "H"
                       # , fig.align = 'center'
                       )
 # knitr::opts_knit$set(base.url = "../") #relative path for .html output file
 # knitr::opts_knit$set(root.dir = "../") #relative path for chunks within .rmd files
 options(scipen=999)
 options(kableExtra.auto_format = FALSE)
 rm(list=ls())
 options(knitr.kable.NA = '')
 options(knitr.graphics.error = FALSE)
 Sys.setlocale("LC_ALL", "ES_ES.UTF-8")
```

```{r}
# This document was last modified at {{< modified >}}
# 
# and it was last rendered at {{< now >}}

```

{{< include 01-introduction.qmd >}}

{{< include 02-antecedentes.qmd >}}

{{< include 03-methods.qmd >}}

{{< include 04-analisis.qmd >}}

{{< include 05-discussion.qmd >}}

